#ifndef MESSAGEDEFINE_H
#define MESSAGEDEFINE_H

#define REQUEST_BUYERINFO 20000

#define REQUEST_SEARCH    20002


#define NOTIFY_VEGETABLEINFO		40000

#define NOTIFY_BUYER_INFO			40002

#define NOTIFY_SEARCH_INFO			40004

#endif // MESSAGEDEFINE_H
